name: gromka-show

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gromka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gromka_db_prod:/var/lib/postgresql/data

  app:
    image: gromka-show-app:prod
    pull_policy: never
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gromka?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node .output/server/index.mjs"

volumes:
  gromka_db_prod:

